# **Import Modules & Read data**

In [1]:
import numpy as np
import pandas as pd

In [2]:
dataRaw=pd.read_csv('us_final.csv',header=0)

In [3]:
dataRaw = dataRaw.drop(['SeverityRatio_15days'], axis=1)

In [4]:
data = dataRaw

In [5]:
data2 = data[[
 'Severity_Bisection',

 'Start_Lat',
 'Start_Lng',
 'Temperature(F)',
 'Wind_Chill(F)',
 'Humidity(%)',
 'Pressure(in)',
 'Visibility(mi)',
 'Wind_Speed(mph)',
 'Precipitation(in)',
    
 'Weather_Condition',
 'Side',
 'State',
 'Month',
 'Weekday',
 'Light',
 'Highway',
   
 'Bisection_WeatherCondition',
 'Visibility_Bisection',
 'Bisection_City',
 'Bisection_County',
 'Bisection_State',

 'Amenity',
 'Bump',
 'Crossing',
 'Give_Way',
 'Junction',
 'No_Exit',
 'Railway',
 'Roundabout',
 'Station',
 'Stop',
 'Traffic_Calming',
 'Traffic_Signal',

 'SeverityRatio_Weekday',
 'SeverityRatio_Month',
 'SeverityRatio_Light',
 'SeverityRatio_WeatherCondition',
 'SeverityRatio_Visibility',
 'SeverityRatio_City',
 'SeverityRatio_County',
 'SeverityRatio_State',
 'SeverityRatio_Road',
 'SeverityRatio_HighWay',
 'SeverityRatio_30days',
 'SeverityRatio_60days',
 'SeverityRatio_90days',
 
 'DeathRate',
 'DeathRate2']]

In [6]:
data2.columns.to_list()

['Severity_Bisection',
 'Start_Lat',
 'Start_Lng',
 'Temperature(F)',
 'Wind_Chill(F)',
 'Humidity(%)',
 'Pressure(in)',
 'Visibility(mi)',
 'Wind_Speed(mph)',
 'Precipitation(in)',
 'Weather_Condition',
 'Side',
 'State',
 'Month',
 'Weekday',
 'Light',
 'Highway',
 'Bisection_WeatherCondition',
 'Visibility_Bisection',
 'Bisection_City',
 'Bisection_County',
 'Bisection_State',
 'Amenity',
 'Bump',
 'Crossing',
 'Give_Way',
 'Junction',
 'No_Exit',
 'Railway',
 'Roundabout',
 'Station',
 'Stop',
 'Traffic_Calming',
 'Traffic_Signal',
 'SeverityRatio_Weekday',
 'SeverityRatio_Month',
 'SeverityRatio_Light',
 'SeverityRatio_WeatherCondition',
 'SeverityRatio_Visibility',
 'SeverityRatio_City',
 'SeverityRatio_County',
 'SeverityRatio_State',
 'SeverityRatio_Road',
 'SeverityRatio_HighWay',
 'SeverityRatio_30days',
 'SeverityRatio_60days',
 'SeverityRatio_90days',
 'DeathRate',
 'DeathRate2']

# **Label Encoding**

In [7]:
data2.replace({False: 0, True: 1}, inplace=True)

/tmp/ipykernel_29366/1007615547.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2.replace({False: 0, True: 1}, inplace=True)


In [8]:
# data2['DayNight'].replace({'Dark': 0, 'Dim': 1, 'Bright': 2}, inplace=True)

In [9]:
data2['Bisection_WeatherCondition'].replace({'BadWeather': 0, 'GoodWeather': 1}, inplace=True)

/tmp/ipykernel_29366/210834288.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['Bisection_WeatherCondition'].replace({'BadWeather': 0, 'GoodWeather': 1}, inplace=True)


In [10]:
data2['Side'].replace({'L': 0, 'R': 1}, inplace=True)

/tmp/ipykernel_29366/2306237467.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['Side'].replace({'L': 0, 'R': 1}, inplace=True)


In [11]:
data2['Visibility_Bisection'].replace({'level_1': 0, 'level_2': 1}, inplace=True)

/tmp/ipykernel_29366/93960287.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['Visibility_Bisection'].replace({'level_1': 0, 'level_2': 1}, inplace=True)


In [12]:
data2['Bisection_City'].replace({'BadCity': 0, 'GoodCity': 1}, inplace=True)

/tmp/ipykernel_29366/2689946353.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['Bisection_City'].replace({'BadCity': 0, 'GoodCity': 1}, inplace=True)


In [13]:
data2['Bisection_County'].replace({'BadCounty': 0, 'GoodCounty': 1}, inplace=True)

/tmp/ipykernel_29366/252464064.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['Bisection_County'].replace({'BadCounty': 0, 'GoodCounty': 1}, inplace=True)


In [14]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [15]:
# labelencoder = LabelEncoder()
# data2.insert(1,'State_le', labelencoder.fit_transform(data['State']))
# # data2.insert(1,'RoadType_le', labelencoder.fit_transform(data['RoadType']))
# data2.insert(1,'City_le', labelencoder.fit_transform(data['City']))
# data2.insert(1,'County_le', labelencoder.fit_transform(data['County']))
# data2.insert(1,'Weather_Condition_le', labelencoder.fit_transform(data['Weather_Condition']))
# data2.insert(1,'Month_le', labelencoder.fit_transform(data['Month']))
# # data2.insert(1,'Highway_Bisection_le', labelencoder.fit_transform(data['Highway_Bisection']))
# data2.insert(1,'Highway_Bisection_le', labelencoder.fit_transform(data['Highway_Bisection']))
# data2.insert(1,'State_Bisection_le', labelencoder.fit_transform(data['State_Bisection']))


# # City, County, State, Weather_Condition, Month, Highway_Bisection, State_Bisection


In [16]:
labelencoder = LabelEncoder()
data2.insert(1,'State_le', labelencoder.fit_transform(data['State']))
# data2.insert(1,'RoadType_le', labelencoder.fit_transform(data['RoadType']))
# data2.insert(1,'City_le', labelencoder.fit_transform(data['City']))
# data2.insert(1,'County_le', labelencoder.fit_transform(data['County']))
data2.insert(1,'Weather_Condition_le', labelencoder.fit_transform(data['Weather_Condition']))
data2.insert(1,'Month_le', labelencoder.fit_transform(data['Month']))
# data2.insert(1,'Highway_Bisection_le', labelencoder.fit_transform(data['Highway_Bisection']))
data2.insert(1,'Highway_le', labelencoder.fit_transform(data['Highway']))
data2.insert(1,'Bisection_State_le', labelencoder.fit_transform(data['Bisection_State']))
data2.insert(1,'Weekday_le', labelencoder.fit_transform(data['Weekday']))
data2.insert(1,'Light_le', labelencoder.fit_transform(data['Light']))


data2 = data2.drop(['State',  'Weather_Condition', 'Month', 'Highway', 'Bisection_State', 'Light','Weekday'], axis=1)

# City, County, State, Weather_Condition, Month, Highway_Bisection, State_Bisection


In [17]:
data2.columns.to_list()

['Severity_Bisection',
 'Light_le',
 'Weekday_le',
 'Bisection_State_le',
 'Highway_le',
 'Month_le',
 'Weather_Condition_le',
 'State_le',
 'Start_Lat',
 'Start_Lng',
 'Temperature(F)',
 'Wind_Chill(F)',
 'Humidity(%)',
 'Pressure(in)',
 'Visibility(mi)',
 'Wind_Speed(mph)',
 'Precipitation(in)',
 'Side',
 'Bisection_WeatherCondition',
 'Visibility_Bisection',
 'Bisection_City',
 'Bisection_County',
 'Amenity',
 'Bump',
 'Crossing',
 'Give_Way',
 'Junction',
 'No_Exit',
 'Railway',
 'Roundabout',
 'Station',
 'Stop',
 'Traffic_Calming',
 'Traffic_Signal',
 'SeverityRatio_Weekday',
 'SeverityRatio_Month',
 'SeverityRatio_Light',
 'SeverityRatio_WeatherCondition',
 'SeverityRatio_Visibility',
 'SeverityRatio_City',
 'SeverityRatio_County',
 'SeverityRatio_State',
 'SeverityRatio_Road',
 'SeverityRatio_HighWay',
 'SeverityRatio_30days',
 'SeverityRatio_60days',
 'SeverityRatio_90days',
 'DeathRate',
 'DeathRate2']

In [18]:
# cols_to_norm = ['Start_Lat',
#  'Start_Lng',

#  'Temperature(F)',
#  'Wind_Chill(F)',
#  'Humidity(%)',
#  'Pressure(in)',
#  'Visibility(mi)',
#  'Wind_Speed(mph)',
#  'Precipitation(in)',]
# data2[cols_to_norm] = data2[cols_to_norm].apply(lambda x: (x - x.min()) / (x.max() - x.min())*0.6+0.2)

In [19]:
data2

Severity_Bisection  Light_le  Weekday_le  Bisection_State_le  \
0                         0         2           1                   0   
1                         0         2           1                   0   
2                         1         2           5                   0   
3                         1         2           5                   0   
4                         0         2           2                   0   
...                     ...       ...         ...                 ...   
2213157                   0         2           0                   1   
2213158                   0         2           0                   0   
2213159                   0         2           0                   1   
2213160                   0         0           0                   0   
2213161                   0         0           0                   0   

         Highway_le  Month_le  Weather_Condition_le  State_le  Start_Lat  \
0                 2         7                    66        33  39.938490   
1                 0         7                    49        33  39.970430   
2                 0         7                    49        33  41.474552   
3                 2         7                    49        33  41.479740   
4                 2         7                    69        15  38.191050   
...             ...       ...                   ...       ...        ...   
2213157           2         2                     7        24  45.672460   
2213158           2         2                     7        36  39.934154   
2213159           0         2                     7        38  33.938415   
2213160           2         2                    66        25  35.815495   
2213161           0         2                    66        41  29.887021   

          Start_Lng  ...  SeverityRatio_City  SeverityRatio_County  \
0        -82.848490  ...            0.215190              0.267530   
1        -83.019620  ...            0.215190              0.267530   
2        -81.711522  ...            0.184287              0.196343   
3        -81.666700  ...            0.184287              0.196343   
4        -85.719020  ...            0.134774              0.157684   
...             ...  ...                 ...                   ...   
2213157 -111.006084  ...            0.005613              0.009982   
2213158  -76.686683  ...            0.063170              0.063055   
2213159  -80.979593  ...            0.033770              0.024339   
2213160  -78.690847  ...            0.019512              0.024187   
2213161  -95.424211  ...            0.070980              0.078303   

         SeverityRatio_State  SeverityRatio_Road  SeverityRatio_HighWay  \
0                   0.182498            0.000000               0.034571   
1                   0.182498            0.349823               0.070680   
2                   0.182498            0.000000               0.070680   
3                   0.182498            0.000000               0.034571   
4                   0.177346            0.202785               0.034571   
...                      ...                 ...                    ...   
2213157             0.015171            0.000000               0.034571   
2213158             0.090529            0.112832               0.034571   
2213159             0.018754            0.000000               0.070680   
2213160             0.071042            0.000000               0.034571   
2213161             0.084803            0.000000               0.070680   

         SeverityRatio_30days  SeverityRatio_60days  SeverityRatio_90days  \
0                    0.824561              0.685185              0.685185   
1                    0.824561              0.685185              0.685185   
2                    0.745763              0.609091              0.672727   
3                    0.745763              0.609091              0.672727   
4                    0.909091              0.627273              0.690909   
...            

# **Train-Test Split**

In [20]:
numSeveritySevere = sum(data2['Severity_Bisection']==1)
print(numSeveritySevere)

dataSeverityMinor = data2[data2['Severity_Bisection']==0]
#dataSeverityMinor

128427


In [21]:
dataSeverityMinorTmp = dataSeverityMinor.sample(n=numSeveritySevere, replace=True)
dataSeveritySevere = data2[data2['Severity_Bisection']==1]

In [22]:
dataSeveritySevere

Severity_Bisection  Light_le  Weekday_le  Bisection_State_le  \
2                         1         2           5                   0   
3                         1         2           5                   0   
7                         1         2           3                   0   
15                        1         0           0                   0   
18                        1         1           1                   0   
...                     ...       ...         ...                 ...   
2212450                   1         2           0                   0   
2212574                   1         2           0                   0   
2212781                   1         2           0                   1   
2213020                   1         3           0                   0   
2213107                   1         0           0                   0   

         Highway_le  Month_le  Weather_Condition_le  State_le  Start_Lat  \
2                 0         7                    49        33  41.474552   
3                 2         7                    49        33  41.479740   
7                 0         7                    57        33  41.463557   
15                0         7                    71        36  40.068590   
18                0         7                    49         5  41.106740   
...             ...       ...                   ...       ...        ...   
2212450           0         2                    57         4  40.388965   
2212574           2         2                     7        36  39.931236   
2212781           3         2                    13         8  28.553184   
2213020           3         2                    13        31  39.261507   
2213107           3         2                    71         9  33.756576   

          Start_Lng  ...  SeverityRatio_City  SeverityRatio_County  \
2        -81.711522  ...            0.184287              0.196343   
3        -81.666700  ...            0.184287              0.196343   
7        -82.053729  ...            0.226721              0.411765   
15       -75.670050  ...            0.107212              0.063424   
18       -73.414460  ...            0.029480              0.069091   
...             ...  ...                 ...                   ...   
2212450 -104.993525  ...            0.218841              1.466960   
2212574  -76.691833  ...            0.063170              0.063055   
2212781  -81.347912  ...            0.016352              0.019600   
2213020 -119.582354  ...            0.026095              0.072183   
2213107  -84.468437  ...            0.182691              0.184334   

         SeverityRatio_State  SeverityRatio_Road  SeverityRatio_HighWay  \
2                   0.182498            0.000000               0.070680   
3                   0.182498            0.000000               0.034571   
7                   0.182498            0.349823               0.070680   
15                  0.090529            0.112832               0.070680   
18                  0.118682            0.000000               0.070680   
...                      ...                 ...                    ...   
2212450             0.900387            0.571745               0.070680   
2212574             0.090529            0.112832               0.034571   
2212781             0.025859            0.003349               0.000000   
2213020             0.081569            0.000000               0.000000   
2213107             0.244619            0.166353               0.034571   

         SeverityRatio_30days  SeverityRatio_60days  SeverityRatio_90days  \
2                    0.745763              0.609091              0.672727   
3                    0.745763              0.609091              0.672727   
7                    0.851064              0.610619              0.672566   
15                   0.773585              0.583333              0.641667   
18                   1.000000              0.581967              0.639344   
...            

In [23]:
data3 = pd.concat([dataSeverityMinorTmp, dataSeveritySevere])
data3 = data3.reset_index(drop=True)

In [24]:
data3.columns.to_list()

['Severity_Bisection',
 'Light_le',
 'Weekday_le',
 'Bisection_State_le',
 'Highway_le',
 'Month_le',
 'Weather_Condition_le',
 'State_le',
 'Start_Lat',
 'Start_Lng',
 'Temperature(F)',
 'Wind_Chill(F)',
 'Humidity(%)',
 'Pressure(in)',
 'Visibility(mi)',
 'Wind_Speed(mph)',
 'Precipitation(in)',
 'Side',
 'Bisection_WeatherCondition',
 'Visibility_Bisection',
 'Bisection_City',
 'Bisection_County',
 'Amenity',
 'Bump',
 'Crossing',
 'Give_Way',
 'Junction',
 'No_Exit',
 'Railway',
 'Roundabout',
 'Station',
 'Stop',
 'Traffic_Calming',
 'Traffic_Signal',
 'SeverityRatio_Weekday',
 'SeverityRatio_Month',
 'SeverityRatio_Light',
 'SeverityRatio_WeatherCondition',
 'SeverityRatio_Visibility',
 'SeverityRatio_City',
 'SeverityRatio_County',
 'SeverityRatio_State',
 'SeverityRatio_Road',
 'SeverityRatio_HighWay',
 'SeverityRatio_30days',
 'SeverityRatio_60days',
 'SeverityRatio_90days',
 'DeathRate',
 'DeathRate2']

In [25]:
labels = data3['Severity_Bisection']
data3 = data3.drop(['Severity_Bisection'], axis=1)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data3, labels,test_size=0.2, random_state=100)

In [26]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256854 entries, 0 to 256853
Data columns (total 48 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   Light_le                        256854 non-null  int64  
 1   Weekday_le                      256854 non-null  int64  
 2   Bisection_State_le              256854 non-null  int64  
 3   Highway_le                      256854 non-null  int64  
 4   Month_le                        256854 non-null  int64  
 5   Weather_Condition_le            256854 non-null  int64  
 6   State_le                        256854 non-null  int64  
 7   Start_Lat                       256854 non-null  float64
 8   Start_Lng                       256854 non-null  float64
 9   Temperature(F)                  256854 non-null  float64
 10  Wind_Chill(F)                   256854 non-null  float64
 11  Humidity(%)                     256854 non-null  float64
 12  Pressure(in)    

# **XGBOOST**

In [27]:
from xgboost.sklearn import XGBClassifier
xgbc = XGBClassifier(        
        n_estimators=100,     #樹的個數
        learning_rate= 0.1,    # 如同學習率 
        max_depth=20,       # 構建樹的深度，越大越容易過擬合    
        subsample=1,         # 隨機取樣訓練樣本 訓練例項的子取樣比
        gamma=0,         # 用於控制是否後剪枝的引數,越大越保守，一般0.1、0.2這樣子
        reg_lambda=2,#0.8,   #1       # 控制模型複雜度的權重值的L2正則化項引數，引數越大，模型越不容易過擬合。
        max_delta_step=0,        #最大增量步長，我們允許每個樹的權重估計。
        colsample_bytree=1,         # 生成樹時進行的列取樣 
        min_child_weight=0.01, 
                     # 這個引數預設是 1，是每個葉子裡面 h 的和至少是多少，對正負樣本不均衡時的 0-1 分類而言
                     # 假設 h 在 0.01 附近，min_child_weight 為 1 意味著葉子節點中最少需要包含 100 個樣本。
                     #這個引數非常影響結果，控制葉142子節點中二階導的和的最小值，該引數值越小，越容易 overfitting。
        seed=999,   #隨機種子
#        reg_alpha=0,        # L1 正則項引數
        #scale_pos_weight=1,        #如果取值大於0的話，在類別樣本不平衡的情況下有助於快速收斂。平衡正負權重
        #objective= 'multi:softmax',         #多分類的問題 指定學習任務和相應的學習目標
        #num_class=10,        # 類別數，多分類與 multisoftmax 並用
#        silent=0 ,        # 設定成1則沒有執行資訊輸出，最好是設定為0.是否在執行升級時列印訊息。
#        nthread=4,        # cpu 執行緒數 預設最大
        #eval_metric= 'auc'
)


/home/kiwi/anaconda3/envs/tcfst/lib/python3.9/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index


In [28]:
xgbc.fit(X_train, y_train)
XGB_pred=xgbc.predict(X_test)
print(XGB_pred)

/home/kiwi/anaconda3/envs/tcfst/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/home/kiwi/anaconda3/envs/tcfst/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):


[22:13:32] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[1 0 1 ... 0 0 0]


In [29]:
XGBtrain_score=xgbc.score(X_train, y_train)
print(XGBtrain_score)

0.9971481825747142


In [30]:
XGBtest_score=xgbc.score(X_test,y_test)
print('The Accuracy of XGBOOST Classifier on testing set:', XGBtest_score)

The Accuracy of XGBOOST Classifier on testing set: 0.9105331801989449


In [31]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test,XGB_pred))
print(confusion_matrix(y_test,XGB_pred))

              precision    recall  f1-score   support

           0       0.92      0.90      0.91     25710
           1       0.90      0.92      0.91     25661

    accuracy                           0.91     51371
   macro avg       0.91      0.91      0.91     51371
weighted avg       0.91      0.91      0.91     51371

[[23082  2628]
 [ 1968 23693]]


# C4.5 - CART

In [32]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

In [33]:
# Create Decision Tree classifer object
# max_depth=5,min_samples_leaf=20 決定修剪的Threshole
CartC45 = DecisionTreeClassifier(criterion="gini",max_depth=5,min_samples_leaf=20)  #CART-->gini c4.5-->entropy min_samples_leaf=20, max_depth=4

# Train Decision Tree Classifer
CartC45.fit(X_train,y_train)
CartC45_pred =CartC45.predict(X_test)
print(CartC45_pred)

[1 0 1 ... 0 0 0]


In [34]:
print(y_test)

192673    1
113802    0
237216    1
28345     0
242396    1
         ..
163278    1
54428     0
34676     0
101953    0
245346    1
Name: Severity_Bisection, Length: 51371, dtype: int64


In [35]:
CartC45train_score=CartC45.score(X_train, y_train)
print(CartC45train_score)

0.8838541387852037


In [36]:
CartC45test_score=CartC45.score(X_test,y_test)
print('The Accuracy of CART/C4.5 Classifier on testing set:', CartC45test_score)

The Accuracy of CART/C4.5 Classifier on testing set: 0.882268205797045


In [37]:
print(classification_report(y_test,CartC45_pred))
print(confusion_matrix(y_test,CartC45_pred))

              precision    recall  f1-score   support

           0       0.90      0.86      0.88     25710
           1       0.87      0.90      0.88     25661

    accuracy                           0.88     51371
   macro avg       0.88      0.88      0.88     51371
weighted avg       0.88      0.88      0.88     51371

[[22174  3536]
 [ 2512 23149]]


# ExtraTrees

In [38]:
from sklearn.ensemble import ExtraTreesClassifier
ETreec = ExtraTreesClassifier(max_depth=30,n_estimators=10,criterion='gini')

In [39]:
ETreec.fit(X_train, y_train)
ETree_pred=ETreec.predict(X_test)
print(ETree_pred)

[1 0 1 ... 0 0 0]


In [40]:
ETreetrain_score=ETreec.score(X_train, y_train)
print(ETreetrain_score)

0.994666225429841


In [41]:
ETreetest_score=ETreec.score(X_test,y_test)
print('The Accuracy of ExtraTrees Classifier on testing set:', ETreetest_score)


The Accuracy of ExtraTrees Classifier on testing set: 0.9007611298203266


In [42]:
print(classification_report(y_test,ETree_pred))
print(confusion_matrix(y_test,ETree_pred))

              precision    recall  f1-score   support

           0       0.90      0.90      0.90     25710
           1       0.90      0.91      0.90     25661

    accuracy                           0.90     51371
   macro avg       0.90      0.90      0.90     51371
weighted avg       0.90      0.90      0.90     51371

[[23045  2665]
 [ 2433 23228]]


# RandomForest

In [43]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, 
                       min_samples_leaf=40, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
#rfc=RandomForestClassifier()#使用預設直

In [44]:
rfc.fit(X_train, y_train)
RF_pred=rfc.predict(X_test)
print(RF_pred)

[1 0 1 ... 0 0 0]


In [45]:
RFtrain_score=rfc.score(X_train, y_train)
print(RFtrain_score)

0.9015490332533591


In [46]:
RFtest_score=rfc.score(X_test,y_test)
print('The Accuracy of RandomForest Classifier on testing set:', RFtest_score)

The Accuracy of RandomForest Classifier on testing set: 0.8979385256272995


In [47]:
print(classification_report(y_test,RF_pred))
print(confusion_matrix(y_test,RF_pred))

              precision    recall  f1-score   support

           0       0.91      0.88      0.90     25710
           1       0.89      0.91      0.90     25661

    accuracy                           0.90     51371
   macro avg       0.90      0.90      0.90     51371
weighted avg       0.90      0.90      0.90     51371

[[22662  3048]
 [ 2195 23466]]


# AdaBoost

In [48]:
from sklearn.ensemble import AdaBoostClassifier#若為數值要改成  AdaBoostregressor
AdaBoostc = AdaBoostClassifier(random_state=0)

In [49]:
AdaBoostc.fit(X_train, y_train)
AdaBoostc_pred=AdaBoostc.predict(X_test)
print(AdaBoostc_pred)

[1 0 1 ... 0 0 0]


In [50]:
AdaBoosttrain_score=AdaBoostc.score(X_train, y_train)
print(AdaBoosttrain_score)

0.877347517799526


In [51]:
AdaBoosttest_score=AdaBoostc.score(X_test,y_test)
print('The Accuracy of AdaBoost Classifier on testing set:', AdaBoosttest_score)

The Accuracy of AdaBoost Classifier on testing set: 0.8787642833505285


In [52]:
print(classification_report(y_test,AdaBoostc_pred))
print(confusion_matrix(y_test,AdaBoostc_pred))

              precision    recall  f1-score   support

           0       0.88      0.87      0.88     25710
           1       0.87      0.88      0.88     25661

    accuracy                           0.88     51371
   macro avg       0.88      0.88      0.88     51371
weighted avg       0.88      0.88      0.88     51371

[[22458  3252]
 [ 2976 22685]]


# **LightGBM**

In [53]:
import numpy as np
import pandas as pd
import lightgbm as lgb
from sklearn.preprocessing import LabelBinarizer


In [54]:
import lightgbm as lgb
lgbmc = lgb.LGBMClassifier()


In [55]:
lgbmc.fit(X_train, y_train)
LGBM_pred=lgbmc.predict(X_test)
print(LGBM_pred)

[1 0 1 ... 0 0 0]


In [56]:
LGBMtrain_score=lgbmc.score(X_train, y_train)
print(LGBMtrain_score)

0.9002399225240044


In [57]:
LGBMtest_score=lgbmc.score(X_test,y_test)
print('The Accuracy of LightGBM Classifier on testing set:', LGBMtest_score)

The Accuracy of LightGBM Classifier on testing set: 0.8981331879854393


In [58]:
print(classification_report(y_test,LGBM_pred))
print(confusion_matrix(y_test,LGBM_pred))

              precision    recall  f1-score   support

           0       0.91      0.88      0.90     25710
           1       0.88      0.92      0.90     25661

    accuracy                           0.90     51371
   macro avg       0.90      0.90      0.90     51371
weighted avg       0.90      0.90      0.90     51371

[[22651  3059]
 [ 2174 23487]]


# ***CatBOOST***



In [59]:
# !pip install catboost
# !pip install ipywidgets
!jupyter nbextension enable --py widgetsnbextension

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK


In [60]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# plt.style.use('ggplot') 
# import seaborn as sns
from catboost import CatBoostClassifier, Pool, cv
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import VarianceThreshold


In [61]:
CatBc = CatBoostClassifier(iterations=20,
  learning_rate=1,
  depth=2,
  loss_function='MultiClass')

In [62]:
CatBc.fit(X_train, y_train)
CatB_pred=CatBc.predict(X_test)
# print(CatB_pred)

0:	learn: 0.4274028	total: 62.8ms	remaining: 1.19s
1:	learn: 0.3566719	total: 79.5ms	remaining: 716ms
2:	learn: 0.3369566	total: 92.5ms	remaining: 524ms
3:	learn: 0.3316021	total: 105ms	remaining: 419ms
4:	learn: 0.3265643	total: 118ms	remaining: 353ms
5:	learn: 0.3240235	total: 134ms	remaining: 312ms
6:	learn: 0.3193366	total: 147ms	remaining: 272ms
7:	learn: 0.3175700	total: 158ms	remaining: 238ms
8:	learn: 0.3151609	total: 170ms	remaining: 208ms
9:	learn: 0.3137161	total: 182ms	remaining: 182ms
10:	learn: 0.3117316	total: 194ms	remaining: 159ms
11:	learn: 0.3100703	total: 207ms	remaining: 138ms
12:	learn: 0.3088993	total: 218ms	remaining: 117ms
13:	learn: 0.3075511	total: 230ms	remaining: 98.4ms
14:	learn: 0.3067578	total: 242ms	remaining: 80.5ms
15:	learn: 0.3061882	total: 253ms	remaining: 63.3ms
16:	learn: 0.3050657	total: 268ms	remaining: 47.2ms
17:	learn: 0.3041302	total: 281ms	remaining: 31.2ms
18:	learn: 0.3032631	total: 293ms	remaining: 15.4ms
19:	learn: 0.3026820	total: 305m

In [63]:
CatBtrain_score=CatBc.score(X_train, y_train)
print(CatBtrain_score)

0.8840926013344169


In [64]:
CatBest_score=CatBc.score(X_test,y_test)
print('The Accuracy of CatBOOST Classifier on testing set:',CatBest_score)

The Accuracy of CatBOOST Classifier on testing set: 0.8858889256584455


In [65]:
print(classification_report(y_test,CatB_pred))
print(confusion_matrix(y_test,CatB_pred))

              precision    recall  f1-score   support

           0       0.90      0.87      0.88     25710
           1       0.87      0.90      0.89     25661

    accuracy                           0.89     51371
   macro avg       0.89      0.89      0.89     51371
weighted avg       0.89      0.89      0.89     51371

[[22382  3328]
 [ 2534 23127]]
